#############################################################################
# Makefile for building: Talkeron.app/Contents/MacOS/Talkeron
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Talkeron.pro
# Template: app
# Command: /Applications/Qt5.7.0/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Talkeron.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -F/Applications/Qt5.7.0/5.7/clang_64/lib
QMAKE         = /Applications/Qt5.7.0/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Talkeron1.0.0
DISTDIR = /Users/ln/TalkeronHome/Projects/Talkeron/Talkeron/.tmp/Talkeron1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Applications/Qt5.7.0/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Applications/Qt5.7.0/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/cmdcompileresult.cpp \
		src/cmdtextedit.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/taskblock.cpp \
		src/taskscrollarea.cpp \
		src/taskthread.cpp moc_cmdtextedit.cpp \
		moc_mainwindow.cpp \
		moc_taskthread.cpp
OBJECTS       = cmdcompileresult.o \
		cmdtextedit.o \
		main.o \
		mainwindow.o \
		taskblock.o \
		taskscrollarea.o \
		taskthread.o \
		moc_cmdtextedit.o \
		moc_mainwindow.o \
		moc_taskthread.o
DIST          = createicons.src \
		TalkeronAssist/Talkeron.talk \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		Talkeron.pro src/cmdcompileresult.h \
		src/cmdtextedit.h \
		src/mainwindow.h \
		src/talkerxml.h \
		src/taskblock.h \
		src/taskscrollarea.h \
		src/taskthread.h src/cmdcompileresult.cpp \
		src/cmdtextedit.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/taskblock.cpp \
		src/taskscrollarea.cpp \
		src/taskthread.cpp
QMAKE_TARGET  = Talkeron
DESTDIR       = 
TARGET        = Talkeron.app/Contents/MacOS/Talkeron


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d Talkeron.app/Contents/MacOS/ || mkdir -p Talkeron.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Talkeron.pro /Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf /Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf \
		/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf \
		Talkeron.pro \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/QtXml.prl \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Talkeron.pro
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_pre.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qdevice.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/device_config.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/unix.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/mac.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/macx.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/sanitize.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/common/clang-mac.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/qconfig.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_functions.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt_config.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_pre.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resolve_config.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/default_post.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/sdk.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/default_post.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qml_debug.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/warn_on.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/qt.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/resources.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/moc.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/opengl.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/uic.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/unix/thread.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/file_copies.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/mac/rez.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/testcase_targets.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/exceptions.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/yacc.prf:
/Applications/Qt5.7.0/5.7/clang_64/mkspecs/features/lex.prf:
Talkeron.pro:
/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/QtXml.prl:
/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Talkeron.pro

qmake_all: FORCE

Talkeron.app/Contents/PkgInfo: 
	@test -d Talkeron.app/Contents || mkdir -p Talkeron.app/Contents
	@$(DEL_FILE) Talkeron.app/Contents/PkgInfo
	@echo "APPL????" > Talkeron.app/Contents/PkgInfo
Talkeron.app/Contents/Resources/empty.lproj: 
	@test -d Talkeron.app/Contents/Resources || mkdir -p Talkeron.app/Contents/Resources
	@touch Talkeron.app/Contents/Resources/empty.lproj
	
Talkeron.app/Contents/Info.plist: 
	@test -d Talkeron.app/Contents || mkdir -p Talkeron.app/Contents
	@$(DEL_FILE) Talkeron.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Talkeron,g" -e "s,@ICON@,appicon.icns,g" -e "s,@EXECUTABLE@,Talkeron,g" -e "s,@LIBRARY@,Talkeron,g" -e "s,@TYPEINFO@,????,g" /Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Talkeron.app/Contents/Info.plist
Talkeron.app/Contents/Resources/appicon.icns: appicon.icns
	@test -d Talkeron.app/Contents/Resources/ || mkdir -p Talkeron.app/Contents/Resources/
	@$(DEL_FILE) Talkeron.app/Contents/Resources/appicon.icns
	@$(COPY_FILE) appicon.icns Talkeron.app/Contents/Resources/appicon.icns

all: Makefile \
		Talkeron.app/Contents/PkgInfo \
		Talkeron.app/Contents/Resources/empty.lproj \
		Talkeron.app/Contents/Info.plist \
		Talkeron.app/Contents/Resources/appicon.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/cmdcompileresult.h src/cmdtextedit.h src/mainwindow.h src/talkerxml.h src/taskblock.h src/taskscrollarea.h src/taskthread.h $(DISTDIR)/
	$(COPY_FILE) --parents src/cmdcompileresult.cpp src/cmdtextedit.cpp src/main.cpp src/mainwindow.cpp src/taskblock.cpp src/taskscrollarea.cpp src/taskthread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Talkeron.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_cmdtextedit.cpp moc_mainwindow.cpp moc_taskthread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cmdtextedit.cpp moc_mainwindow.cpp moc_taskthread.cpp
moc_cmdtextedit.cpp: /Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/bin/moc
	/Applications/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron/src -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I/usr/lib/c++/v1 -I/usr/local/include -I/usr/lib/clang/4.2/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Applications/Qt5.7.0/5.7/clang_64/lib src/cmdtextedit.h -o moc_cmdtextedit.cpp

moc_mainwindow.cpp: /Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		src/cmdcompileresult.h \
		src/mainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/bin/moc
	/Applications/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron/src -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I/usr/lib/c++/v1 -I/usr/local/include -I/usr/lib/clang/4.2/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Applications/Qt5.7.0/5.7/clang_64/lib src/mainwindow.h -o moc_mainwindow.cpp

moc_taskthread.cpp: /Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		src/taskthread.h \
		/Applications/Qt5.7.0/5.7/clang_64/bin/moc
	/Applications/Qt5.7.0/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Applications/Qt5.7.0/5.7/clang_64/mkspecs/macx-clang -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron -I/Users/ln/TalkeronHome/Projects/Talkeron/Talkeron/src -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtXml.framework/Headers -I/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers -I/usr/lib/c++/v1 -I/usr/local/include -I/usr/lib/clang/4.2/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Applications/Qt5.7.0/5.7/clang_64/lib src/taskthread.h -o moc_taskthread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Applications/Qt5.7.0/5.7/clang_64/bin/uic \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h
	/Applications/Qt5.7.0/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

cmdcompileresult.o: src/cmdcompileresult.cpp src/cmdcompileresult.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmdcompileresult.o src/cmdcompileresult.cpp

cmdtextedit.o: src/cmdtextedit.cpp src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qevent.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmdtextedit.o src/cmdtextedit.cpp

main.o: src/main.cpp src/mainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		src/cmdcompileresult.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		src/cmdcompileresult.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QSizeGrip \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qsizegrip.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QScrollBar \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QTime \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QLine \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qline.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		ui_mainwindow.h \
		src/talkerxml.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

taskblock.o: src/taskblock.cpp src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QProcess \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFile \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfile.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDir \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdir.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h \
		src/mainwindow.h \
		src/cmdcompileresult.h \
		src/taskthread.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskblock.o src/taskblock.cpp

taskscrollarea.o: src/taskscrollarea.cpp src/taskscrollarea.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QScrollArea \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QScrollBar \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskscrollarea.o src/taskscrollarea.cpp

taskthread.o: src/taskthread.cpp src/taskthread.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QThread \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qthread.h \
		src/taskblock.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		src/cmdtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QProcess \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Applications/Qt5.7.0/5.7/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskthread.o src/taskthread.cpp

moc_cmdtextedit.o: moc_cmdtextedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmdtextedit.o moc_cmdtextedit.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_taskthread.o: moc_taskthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskthread.o moc_taskthread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

